import { INITIAL_STATE, type AvatarPreset } from "../types";

const buildPreset = (
  id: string,
  label: string,
  description: string,
  family: string,
  archetype: string,
  variant: string,
  size: string,
  tags: string[],
  state: Partial<AvatarPreset["state"]>,
): AvatarPreset => ({
  id,
  label,
  description,
  family,
  archetype,
  variant,
  size,
  tags,
  state: {
    ...INITIAL_STATE,
    ...state,
  },
});

const BASE_AVATAR_PRESETS: AvatarPreset[] = [
  buildPreset(
    "studio-circle",
    "Studio Circle",
    "Clean circular avatar with soft depth and a subtle online badge.",
    "signature",
    "studio",
    "circle",
    "md",
    ["circle", "status", "clean", "studio"],
    {
      size: "128px",
      radiusMode: "circle",
      shadow: "0 12px 28px rgba(15, 23, 42, 0.12)",
      use3DBadge: "sphere",
      use3DStatus: "ring",
      status: "online",
      statusAnimation: "pulse",
      hoverZoom: true,
      hoverEffect: "scale",
      entranceAnimation: "fade",
      textureEffect: "glass",
      ariaLabel: "Studio circle avatar",
    },
  ),
  buildPreset(
    "glass-portrait",
    "Glass Portrait",
    "Portrait image with glass texture, reflection, and a soft frame.",
    "signature",
    "portrait",
    "glass",
    "md",
    ["glass", "portrait", "photo", "reflection"],
    {
      src: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&h=800&fit=crop",
      alt: "Portrait avatar",
      initials: "AP",
      radiusMode: "rounded",
      radiusValue: 28,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.22)",
      shadow: "0 18px 40px rgba(15, 23, 42, 0.2)",
      opacity: 96,
      filterBrightness: 105,
      filterContrast: 108,
      textureEffect: "glass",
      hoverGrayscale: false,
      hoverEffect: "layout",
      entranceAnimation: "scale",
      ariaLabel: "Glass portrait avatar",
    },
  ),
  buildPreset(
    "cyber-halo",
    "Cyber Halo",
    "Futuristic badge, halo status, and neon accessory treatment.",
    "signature",
    "cyber",
    "halo",
    "md",
    ["cyber", "neon", "halo", "status"],
    {
      initials: "ZX",
      initialsBg: "#0f172a",
      initialsColor: "#e2e8f0",
      radiusMode: "square",
      radiusValue: 18,
      borderWidth: 2,
      borderColor: "#22d3ee",
      shadow: "0 0 0 1px rgba(34,211,238,0.35), 0 0 28px rgba(34,211,238,0.28)",
      status: "busy",
      statusPosition: "top-right",
      statusAnimation: "pulse",
      use3DBadge: "cube",
      use3DStatus: "halo",
      accessoryType: "halo-cyber",
      accessoryColor: "#22d3ee",
      orbitSpeed: "1.8",
      effect3D: "glitch",
      hoverEffect: "layout",
      hoverZoom: true,
      textureEffect: "glitch",
      borderEffect: "glow-pulse",
      entranceAnimation: "slide",
      ariaLabel: "Cyber halo avatar",
    },
  ),
  buildPreset(
    "editorial-monogram",
    "Editorial Monogram",
    "Monogram-first avatar with serif tone and refined framing.",
    "signature",
    "editorial",
    "monogram",
    "md",
    ["editorial", "monogram", "serif", "minimal"],
    {
      src: "",
      initials: "JN",
      initialsBg: "#f8fafc",
      initialsColor: "#0f172a",
      fontFamily: "serif",
      radiusMode: "rounded",
      radiusValue: 48,
      borderWidth: 2,
      borderColor: "#cbd5e1",
      shadow: "0 10px 28px rgba(15,23,42,0.08)",
      effect3D: "none",
      hoverEffect: "none",
      textureEffect: "none",
      borderEffect: "none",
      ariaLabel: "Editorial monogram avatar",
    },
  ),
  buildPreset(
    "crown-leader",
    "Crown Leader",
    "Presence-rich avatar with crown accessory and strong status cue.",
    "signature",
    "premium",
    "leader",
    "md",
    ["crown", "status", "leader", "premium"],
    {
      initials: "AL",
      radiusMode: "circle",
      borderWidth: 1,
      borderColor: "#f8fafc",
      shadow: "0 16px 34px rgba(15,23,42,0.18)",
      status: "away",
      statusPosition: "bottom-right",
      statusAnimation: "pulse",
      badgeCount: "9+",
      use3DBadge: "star",
      badgeAnimate: true,
      accessoryType: "crown",
      accessoryColor: "#fbbf24",
      orbitSpeed: "1.2",
      hoverZoom: true,
      hoverEffect: "float-y",
      entranceAnimation: "fade",
      ariaLabel: "Crown leader avatar",
    },
  ),
  buildPreset(
    "social-stack",
    "Social Stack",
    "Overlapping group preview with stacked spacing and social status.",
    "signature",
    "group",
    "stack",
    "md",
    ["group", "stack", "social", "status"],
    {
      initials: "JS",
      showGroup: true,
      groupSpacing: -16,
      groupLimit: 4,
      groupDirection: "row",
      status: "online",
      statusAnimation: "pulse",
      use3DBadge: "none",
      use3DStatus: "ring",
      hoverZoom: false,
      hoverEffect: "none",
      textureEffect: "none",
      borderEffect: "none",
      ariaLabel: "Social stack avatar group",
    },
  ),
  buildPreset(
    "noir-press",
    "Noir Press",
    "Dark editorial avatar with compact framing and high contrast initials.",
    "signature",
    "editorial",
    "press",
    "sm",
    ["editorial", "dark", "press", "monogram"],
    {
      initials: "NP",
      initialsBg: "#0f172a",
      initialsColor: "#f8fafc",
      size: "112px",
      radiusMode: "rounded",
      radiusValue: 32,
      borderWidth: 2,
      borderColor: "#334155",
      shadow: "0 18px 40px rgba(15,23,42,0.26)",
      status: "none",
      effect3D: "none",
      hoverEffect: "layout",
      textureEffect: "none",
      borderEffect: "none",
      ariaLabel: "Noir press avatar",
    },
  ),
  buildPreset(
    "aura-pair",
    "Aura Pair",
    "Couple-style paired avatar with glowing status and balanced spacing.",
    "signature",
    "group",
    "pair",
    "md",
    ["pair", "glow", "status", "soft"],
    {
      initials: "AP",
      showGroup: true,
      groupSpacing: -10,
      groupLimit: 2,
      groupDirection: "row",
      status: "online",
      statusPosition: "bottom-right",
      statusAnimation: "pulse",
      use3DBadge: "sphere",
      use3DStatus: "ring",
      accessoryType: "orb-float",
      accessoryColor: "#a78bfa",
      orbitSpeed: "1.4",
      hoverZoom: true,
      hoverEffect: "scale",
      textureEffect: "fluid",
      ariaLabel: "Aura pair avatar",
    },
  ),
  buildPreset(
    "soft-ambassador",
    "Soft Ambassador",
    "Calm image avatar with subtle blur, low contrast, and a neutral frame.",
    "signature",
    "portrait",
    "soft",
    "md",
    ["soft", "portrait", "calm", "neutral"],
    {
      src: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=800&fit=crop",
      alt: "Soft ambassador avatar",
      initials: "SA",
      radiusMode: "circle",
      borderWidth: 1,
      borderColor: "rgba(148,163,184,0.4)",
      shadow: "0 10px 24px rgba(15,23,42,0.12)",
      filterBrightness: 102,
      filterContrast: 98,
      filterBlur: 0,
      hoverGrayscale: false,
      hoverEffect: "layout",
      entranceAnimation: "scale",
      ariaLabel: "Soft ambassador avatar",
    },
  ),
  buildPreset(
    "status-ring",
    "Status Ring",
    "Minimal ring-framed avatar with a prominent availability cue.",
    "signature",
    "status",
    "ring",
    "md",
    ["status", "ring", "minimal", "availability"],
    {
      initials: "SR",
      radiusMode: "circle",
      borderWidth: 3,
      borderColor: "#22c55e",
      shadow: "0 0 0 6px rgba(34,197,94,0.08)",
      status: "online",
      statusPosition: "bottom-right",
      statusAnimation: "pulse",
      use3DBadge: "none",
      use3DStatus: "ring",
      hoverZoom: false,
      hoverEffect: "none",
      textureEffect: "none",
      borderEffect: "glow-pulse",
      ariaLabel: "Status ring avatar",
    },
  ),
  buildPreset(
    "monogram-grid",
    "Monogram Grid",
    "Stack-ready monogram variant tuned for dense team layouts.",
    "signature",
    "utility",
    "grid",
    "sm",
    ["monogram", "grid", "team", "compact"],
    {
      initials: "MG",
      initialsBg: "#e2e8f0",
      initialsColor: "#0f172a",
      radiusMode: "square",
      radiusValue: 16,
      borderWidth: 1,
      borderColor: "#cbd5e1",
      shadow: "0 8px 20px rgba(15,23,42,0.1)",
      showGroup: false,
      status: "offline",
      effect3D: "none",
      hoverEffect: "none",
      textureEffect: "none",
      borderEffect: "none",
      ariaLabel: "Monogram grid avatar",
    },
  ),
  buildPreset(
    "product-card",
    "Product Card",
    "Card-like avatar with stronger framing and a polished brand surface.",
    "signature",
    "product",
    "card",
    "lg",
    ["card", "product", "framed", "brand"],
    {
      src: "https://api.dicebear.com/9.x/avataaars/svg?seed=Felix",
      alt: "Product card avatar",
      initials: "PC",
      radiusMode: "rounded",
      radiusValue: 24,
      borderWidth: 2,
      borderColor: "#dbeafe",
      shadow: "0 14px 30px rgba(37,99,235,0.14)",
      status: "away",
      statusPosition: "top-left",
      statusAnimation: "pulse",
      badgeCount: "12",
      use3DBadge: "sphere",
      hoverZoom: true,
      hoverEffect: "float-y",
      textureEffect: "glass",
      ariaLabel: "Product card avatar",
    },
  ),
];

type AvatarTheme = {
  id: string;
  label: string;
  image: string;
  accent: string;
  accentSoft: string;
  surface: string;
  text: string;
};

type AvatarArchetype = {
  id: string;
  label: string;
  description: string;
  tags: string[];
  radiusMode: "circle" | "rounded" | "square";
  radiusValue: number;
  status: "none" | "online" | "offline" | "busy" | "away";
  statusPosition: "top-right" | "bottom-right" | "bottom-left" | "top-left";
  statusAnimation: "none" | "pulse";
  fallbackPriority: "auto" | "initials" | "image" | "status";
  textureEffect: "none" | "glitch" | "fluid" | "glass";
  borderEffect: "none" | "snake" | "heartbeat" | "glow-pulse";
  effect3D: "none" | "tilt" | "glitch" | "pulse";
  use3DBadge: "none" | "sphere" | "cube" | "star";
  use3DStatus: "none" | "ring" | "halo";
  accessoryType: "none" | "crown" | "halo-cyber" | "orb-float";
  hoverEffect: "none" | "layout" | "scale" | "holo-card" | "float-y";
  entranceAnimation: "none" | "fade" | "scale" | "slide";
  showGroup?: boolean;
  groupDirection?: "row" | "column";
  badgeCount?: string;
};

const THEMES: AvatarTheme[] = [
  { id: "slate", label: "Slate", image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=800&fit=crop", accent: "#64748b", accentSoft: "#cbd5e1", surface: "#0f172a", text: "#e2e8f0" },
  { id: "cobalt", label: "Cobalt", image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&h=800&fit=crop", accent: "#3b82f6", accentSoft: "#bfdbfe", surface: "#dbeafe", text: "#0f172a" },
  { id: "emerald", label: "Emerald", image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=800&fit=crop", accent: "#10b981", accentSoft: "#a7f3d0", surface: "#022c22", text: "#ecfdf5" },
  { id: "sunset", label: "Sunset", image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=800&fit=crop&sat=-10", accent: "#f97316", accentSoft: "#fed7aa", surface: "#431407", text: "#ffedd5" },
  { id: "rose", label: "Rose", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&h=800&fit=crop", accent: "#f43f5e", accentSoft: "#fecdd3", surface: "#4c0519", text: "#ffe4e6" },
  { id: "violet", label: "Violet", image: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&h=800&fit=crop", accent: "#8b5cf6", accentSoft: "#ddd6fe", surface: "#2e1065", text: "#f5f3ff" },
  { id: "amber", label: "Amber", image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&h=800&fit=crop", accent: "#f59e0b", accentSoft: "#fde68a", surface: "#451a03", text: "#fef3c7" },
  { id: "mint", label: "Mint", image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=800&fit=crop&sat=10", accent: "#14b8a6", accentSoft: "#99f6e4", surface: "#042f2e", text: "#ccfbf1" },
  { id: "arctic", label: "Arctic", image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&h=800&fit=crop", accent: "#38bdf8", accentSoft: "#bae6fd", surface: "#082f49", text: "#e0f2fe" },
  { id: "cherry", label: "Cherry", image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&h=800&fit=crop", accent: "#e11d48", accentSoft: "#fda4af", surface: "#500724", text: "#fff1f2" },
  { id: "obsidian", label: "Obsidian", image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&h=800&fit=crop&sat=-80", accent: "#334155", accentSoft: "#94a3b8", surface: "#020617", text: "#e2e8f0" },
  { id: "indigo", label: "Indigo", image: "https://images.unsplash.com/photo-1546961329-78bef0414d7c?w=800&h=800&fit=crop", accent: "#6366f1", accentSoft: "#c7d2fe", surface: "#1e1b4b", text: "#eef2ff" },
];

const ARCHETYPES: AvatarArchetype[] = [
  { id: "studio-circle", label: "Studio Circle", description: "Soft depth, online cue, and a polished product avatar.", tags: ["circle", "studio", "status", "clean"], radiusMode: "circle", radiusValue: 999, status: "online", statusPosition: "bottom-right", statusAnimation: "pulse", fallbackPriority: "auto", textureEffect: "glass", borderEffect: "none", effect3D: "none", use3DBadge: "sphere", use3DStatus: "ring", accessoryType: "none", hoverEffect: "scale", entranceAnimation: "fade" },
  { id: "glass-portrait", label: "Glass Portrait", description: "Translucent portrait treatment with a reflective frame.", tags: ["glass", "portrait", "premium", "reflection"], radiusMode: "rounded", radiusValue: 28, status: "none", statusPosition: "bottom-right", statusAnimation: "none", fallbackPriority: "image", textureEffect: "glass", borderEffect: "none", effect3D: "tilt", use3DBadge: "none", use3DStatus: "none", accessoryType: "orb-float", hoverEffect: "holo-card", entranceAnimation: "scale" },
  { id: "cyber-halo", label: "Cyber Halo", description: "Neon accessory stack with glitch texture and halo presence.", tags: ["cyber", "neon", "glitch", "halo"], radiusMode: "square", radiusValue: 18, status: "busy", statusPosition: "top-right", statusAnimation: "pulse", fallbackPriority: "status", textureEffect: "glitch", borderEffect: "glow-pulse", effect3D: "glitch", use3DBadge: "cube", use3DStatus: "halo", accessoryType: "halo-cyber", hoverEffect: "layout", entranceAnimation: "slide" },
  { id: "editorial-monogram", label: "Editorial Monogram", description: "Refined serif initials with restrained framing.", tags: ["editorial", "monogram", "minimal", "serif"], radiusMode: "rounded", radiusValue: 44, status: "none", statusPosition: "bottom-right", statusAnimation: "none", fallbackPriority: "initials", textureEffect: "none", borderEffect: "none", effect3D: "none", use3DBadge: "none", use3DStatus: "none", accessoryType: "none", hoverEffect: "none", entranceAnimation: "fade" },
  { id: "crown-leader", label: "Crown Leader", description: "Premium presence with crown accessory and strong badge treatment.", tags: ["leader", "crown", "badge", "premium"], radiusMode: "circle", radiusValue: 999, status: "away", statusPosition: "top-left", statusAnimation: "pulse", fallbackPriority: "auto", textureEffect: "glass", borderEffect: "heartbeat", effect3D: "pulse", use3DBadge: "star", use3DStatus: "ring", accessoryType: "crown", hoverEffect: "float-y", entranceAnimation: "scale", badgeCount: "9+" },
  { id: "social-stack", label: "Social Stack", description: "Group-ready stack with overlap and readable status behavior.", tags: ["group", "stack", "social", "presence"], radiusMode: "circle", radiusValue: 999, status: "online", statusPosition: "bottom-right", statusAnimation: "pulse", fallbackPriority: "auto", textureEffect: "none", borderEffect: "none", effect3D: "none", use3DBadge: "none", use3DStatus: "ring", accessoryType: "none", hoverEffect: "none", entranceAnimation: "fade", showGroup: true, groupDirection: "row" },
  { id: "noir-press", label: "Noir Press", description: "High-contrast editorial avatar with tight framing.", tags: ["editorial", "dark", "press", "contrast"], radiusMode: "rounded", radiusValue: 32, status: "offline", statusPosition: "bottom-right", statusAnimation: "none", fallbackPriority: "initials", textureEffect: "none", borderEffect: "snake", effect3D: "none", use3DBadge: "none", use3DStatus: "none", accessoryType: "none", hoverEffect: "layout", entranceAnimation: "fade" },
  { id: "aura-pair", label: "Aura Pair", description: "Soft pair treatment with floating accessory and glow.", tags: ["pair", "glow", "soft", "friendly"], radiusMode: "circle", radiusValue: 999, status: "online", statusPosition: "bottom-right", statusAnimation: "pulse", fallbackPriority: "auto", textureEffect: "fluid", borderEffect: "none", effect3D: "pulse", use3DBadge: "sphere", use3DStatus: "ring", accessoryType: "orb-float", hoverEffect: "scale", entranceAnimation: "scale", showGroup: true, groupDirection: "row" },
  { id: "soft-ambassador", label: "Soft Ambassador", description: "Calm portrait profile with subtle motion and gentle filters.", tags: ["portrait", "soft", "neutral", "calm"], radiusMode: "circle", radiusValue: 999, status: "none", statusPosition: "bottom-right", statusAnimation: "none", fallbackPriority: "image", textureEffect: "none", borderEffect: "none", effect3D: "tilt", use3DBadge: "none", use3DStatus: "none", accessoryType: "none", hoverEffect: "layout", entranceAnimation: "scale" },
  { id: "status-ring", label: "Status Ring", description: "Availability-first avatar with strong status geometry.", tags: ["status", "ring", "availability", "minimal"], radiusMode: "circle", radiusValue: 999, status: "online", statusPosition: "bottom-right", statusAnimation: "pulse", fallbackPriority: "status", textureEffect: "none", borderEffect: "glow-pulse", effect3D: "none", use3DBadge: "none", use3DStatus: "ring", accessoryType: "none", hoverEffect: "none", entranceAnimation: "fade" },
  { id: "monogram-grid", label: "Monogram Grid", description: "Structured square avatar for grid-heavy interfaces.", tags: ["grid", "square", "monogram", "utility"], radiusMode: "square", radiusValue: 16, status: "none", statusPosition: "bottom-right", statusAnimation: "none", fallbackPriority: "initials", textureEffect: "none", borderEffect: "snake", effect3D: "none", use3DBadge: "none", use3DStatus: "none", accessoryType: "none", hoverEffect: "none", entranceAnimation: "none" },
  { id: "product-card", label: "Product Card", description: "Product-facing avatar surface with glass and badge cues.", tags: ["product", "card", "brand", "framed"], radiusMode: "rounded", radiusValue: 24, status: "away", statusPosition: "top-left", statusAnimation: "pulse", fallbackPriority: "auto", textureEffect: "glass", borderEffect: "heartbeat", effect3D: "tilt", use3DBadge: "sphere", use3DStatus: "halo", accessoryType: "crown", hoverEffect: "float-y", entranceAnimation: "slide", badgeCount: "12" },
];

const SIZE_PROFILES = [
  { id: "xs", label: "Compact", size: "72px", aspectRatio: "1/1", groupSpacing: -8 },
  { id: "sm", label: "Balanced", size: "96px", aspectRatio: "1/1", groupSpacing: -10 },
  { id: "md", label: "Studio", size: "128px", aspectRatio: "1/1", groupSpacing: -12 },
  { id: "lg", label: "Hero", size: "160px", aspectRatio: "1/1", groupSpacing: -16 },
];

function buildGeneratedPreset(
  theme: AvatarTheme,
  archetype: AvatarArchetype,
  size: (typeof SIZE_PROFILES)[number],
): AvatarPreset {
  return {
    id: `${theme.id}-${archetype.id}-${size.id}`,
    label: `${theme.label} ${archetype.label} ${size.label}`,
    description: `${archetype.description} Tuned with the ${theme.label.toLowerCase()} family and ${size.label.toLowerCase()} sizing.`,
    family: theme.id,
    archetype: archetype.id,
    variant: archetype.label,
    size: size.id,
    tags: [theme.id, archetype.id, size.id, ...archetype.tags],
    state: {
      ...INITIAL_STATE,
      src: theme.image,
      alt: `${theme.label} ${archetype.label} avatar`,
      title: `${theme.label} ${archetype.label}`,
      initials: `${theme.label.slice(0, 1)}${archetype.label.slice(0, 1)}`,
      fallbackPriority: archetype.fallbackPriority,
      size: size.size,
      aspectRatio: size.aspectRatio,
      radiusMode: archetype.radiusMode,
      radiusValue: archetype.radiusMode === "circle" ? Number.parseInt(size.size, 10) : archetype.radiusValue,
      borderWidth: archetype.radiusMode === "square" ? 2 : 1,
      borderColor: theme.accentSoft,
      borderStyle: archetype.id === "monogram-grid" ? "dashed" : "solid",
      borderOffset: archetype.id === "status-ring" ? 4 : 0,
      shadow:
        archetype.effect3D === "none"
          ? `0 12px 28px color-mix(in srgb, ${theme.accent} 20%, transparent)`
          : `0 18px 40px color-mix(in srgb, ${theme.accent} 30%, transparent)`,
      initialsBg: theme.surface,
      initialsColor: theme.text,
      fontFamily:
        archetype.id === "editorial-monogram" || archetype.id === "noir-press"
          ? "Georgia, 'Times New Roman', serif"
          : "Inter, system-ui, sans-serif",
      opacity: archetype.id === "glass-portrait" ? 96 : 100,
      filterGrayscale: archetype.id === "noir-press" ? 28 : 0,
      filterBlur: archetype.id === "glass-portrait" ? 1 : 0,
      filterSepia: archetype.id === "editorial-monogram" ? 8 : 0,
      filterBrightness: archetype.id === "soft-ambassador" ? 104 : 100,
      filterContrast: archetype.id === "cyber-halo" ? 116 : 100,
      status: archetype.status,
      statusPosition: archetype.statusPosition,
      statusAnimation: archetype.statusAnimation,
      badgeCount: archetype.badgeCount ?? "",
      showGroup: archetype.showGroup ?? false,
      groupSpacing: size.groupSpacing,
      groupLimit: archetype.showGroup ? 4 : 5,
      groupDirection: archetype.groupDirection ?? "row",
      hoverZoom: archetype.hoverEffect !== "none",
      hoverGrayscale: archetype.id === "noir-press",
      imageRotation: archetype.effect3D === "tilt" ? -3 : 0,
      imageScale: size.id === "lg" ? 1.04 : 1,
      effect3D: archetype.effect3D,
      use3DBadge: archetype.use3DBadge,
      badgeAnimate: archetype.use3DBadge !== "none",
      use3DStatus: archetype.use3DStatus,
      accessoryType: archetype.accessoryType,
      accessoryColor: theme.accent,
      orbitSpeed: archetype.accessoryType === "none" ? "1" : size.id === "lg" ? "1.4" : "1.1",
      entranceAnimation: archetype.entranceAnimation,
      hoverEffect: archetype.hoverEffect,
      textureEffect: archetype.textureEffect,
      borderEffect: archetype.borderEffect,
      ariaLabel: `${theme.label} ${archetype.label} avatar`,
      ariaRole: archetype.showGroup ? "figure" : "img",
      ariaHidden: false,
    },
  };
}

const GENERATED_AVATAR_PRESETS: AvatarPreset[] = THEMES.flatMap((theme) =>
  ARCHETYPES.flatMap((archetype) =>
    SIZE_PROFILES.map((size) => buildGeneratedPreset(theme, archetype, size)),
  ),
);

export const AVATAR_PRESETS: AvatarPreset[] = [
  ...BASE_AVATAR_PRESETS,
  ...GENERATED_AVATAR_PRESETS,
];
